token: '6077995727:AAFW2TmZHCDePSt4wMeKxfcK3G3ji2Hfbm0'
timeout: 10
setCommands: True
database: ':memory:'

commands:
  start: 'Start the bot'
  new: 'Start a new journey'
  check: 'Check-in for your current journey'
  motivation: 'Send a motivational media'
  task: 'Send a task to achieve'
  ranks: 'List the ranks systems'
  profile: 'See your public profile'
  account: 'See your private informations and settings'

ranks:
  'original':
    name: 'Original'
    score: 0
    levels:
      0: 'Newbie'
      1: 'Scout'
      3: 'Private'
      5: 'Corpolar'
      7: 'Sergent'
      10: 'Master Sergent'
      14: 'Knight'
      21: 'Knight-Luitenant'
      30: 'Knight-Captian'
      60: 'Knight-Champion'
      90: 'Champion Of The Light'
      120: 'Commander'
      150: 'Conquerer'
      180: 'Marshall'
      240: 'Field Marshall'
      300: 'Grand Marshall'
      365: 'High Overlord'
      500: 'The Immortal'
  'memes':
    name: 'Memes'
    score: 30
    levels:
      0: 'Coomer'
      1: 'Doomer'
      3: 'NPC'
      5: 'Blackpill'
      7: 'Former Doomer'
      10: 'Broken Bloomer'
      14: 'Bloomer'
      21: 'Whitepill'
      30: 'Patrick Bateman'
      60: 'Tyler Durden'
      90: 'Thomas Anderson'
      120: 'The Homelander'
      150: 'Ryan Gosling'
      180: 'Grindset'
      240: 'Xandillionaire'
      300: 'Chad'
      365: 'Giga Chad'
      500: 'Sigma'

tasks:
  3: 'Do 10 pushups'